SELECT  ?agent ?token ?tokentype ?asset ?owner
WHERE { 
      ?agent oasis:performs ?agentExe.
      ?agentExe oasis:hasTaskObject ?taskExe.
      ?agentExe oasis:hasTaskOperator ?operator.
      ?operator oasis:refersExactlyTo oabox:mint.
      ?taskExe oasis:refersExactlyTo ?token.
      ?operationOn a ?tokentype.
      ?tokenType rdfs:subClassOf ocether:EthereumTokenERC721.
      FILTER (?tokentype != owl:NamedIndividual)
      FILTER NOT EXISTS { ?operationOn a ocether:BurnedEthereumToken }
      ?asset ocether:isDescribedByEthereumToken ?operationOn.          
      ?token ocether:hasEthereumTokenPerdurantFeature ?feature.
      ?feature a ?ownerFeature.
      FILTER(?ownerFeature = ocether:EthereumWalletOwnerPerdurantFeature)
      FILTER NOT EXISTS {?feature a ocether:DeprecatedEthereumTokenPerdurantFeature.} 
      ?feature ocether:isInTheWalletOf ?owner. 
}      
