PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX oasis: <http://www.dmi.unict.it/oasis.owl#>
PREFIX abox: <http://www.dmi.unict.it/oasis-abox.owl>
SELECT ?agentName
	WHERE { 
                      ?agentName oasis:hasBehavior ?behavior.
                      ?behavior oasis:consistsOfGoalDescription ?goal.
                      ?goal oasis:consistsOfTaskDescription ?task.
                      ?task oasis:hasTaskOperator ?op.
                      ?op oasis:refersExactlyTo abox:compute.
                      ?op oasis:hasTaskObject ?obj.
                      ?obj oasis:refersAsNewTo ?asset.
                      ?asset a oasis:Asset.
                   }